apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DATABASE_URL: bXlzcWw6Ly9yb290OmV4YW1wbGVAZGI6MzMwNi9qZG1fY2Fycw== # Base64 encoded "mysql://root:example@db:3306/jdm_cars"