name: CD Pipeline

on:
  push:
    branches:
      - main  # Se realiza el deploy cuando se hace merge en la rama main

env:
  EC2_PUBLIC_IP: ${{ vars.EC2_PUBLIC_IP }}
  EC2_PEM_FILE: ${{ secrets.EC2_PEM_FILE }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  DATABASE_URL: mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@db:3306/${{ secrets.MYSQL_DATABASE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_FILE }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Ensure project directory exists on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ env.EC2_PUBLIC_IP }} "mkdir -p /home/ec2-user/jdm-cars-app"

      - name: Copy docker-compose.yml to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ec2-key.pem docker-compose.yml ec2-user@${{ env.EC2_PUBLIC_IP }}:/home/ec2-user/jdm-cars-app/docker-compose.yml

      - name: Copy .env file to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ env.EC2_PUBLIC_IP }} "echo 'MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}' > /home/ec2-user/jdm-cars-app/.env"
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ env.EC2_PUBLIC_IP }} "echo 'MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}' >> /home/ec2-user/jdm-cars-app/.env"
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ env.EC2_PUBLIC_IP }} "echo 'DATABASE_URL=${{ env.DATABASE_URL }}' >> /home/ec2-user/jdm-cars-app/.env"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ env.EC2_PUBLIC_IP }} << 'EOF'
            set -e
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/jdm-cars-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/jdm-cars-frontend:latest
            cd /home/ec2-user/jdm-cars-app
            docker-compose down || true
            docker-compose up -d
          EOF